// <auto-generated />
using System;
using Central.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Central.Api.Data.Migrations
{
    [DbContext(typeof(CentralDbContext))]
    partial class CentralDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Central.Core.Models.CanonicalOrder", b =>
                {
                    b.Property<string>("ChannelKey")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text");

                    b.Property<string>("CustomerRef")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("RequiredDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChannelKey", "OrderNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Central.Core.Models.Channel", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScheduleMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Central.Core.Models.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Sku");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Central.Core.Models.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("Central.Core.Models.CanonicalOrder", b =>
                {
                    b.OwnsOne("Central.Core.Models.CanonicalCustomer", "Customer", b1 =>
                        {
                            b1.Property<string>("CanonicalOrderChannelKey")
                                .HasColumnType("text");

                            b1.Property<string>("CanonicalOrderOrderNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.HasKey("CanonicalOrderChannelKey", "CanonicalOrderOrderNumber");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("CanonicalOrderChannelKey", "CanonicalOrderOrderNumber");

                            b1.OwnsOne("Central.Core.Models.CanonicalAddress", "DeliveryAddress", b2 =>
                                {
                                    b2.Property<string>("CanonicalCustomerCanonicalOrderChannelKey")
                                        .HasColumnType("text");

                                    b2.Property<string>("CanonicalCustomerCanonicalOrderOrderNumber")
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .HasColumnType("text");

                                    b2.Property<string>("County")
                                        .HasColumnType("text");

                                    b2.Property<string>("Line1")
                                        .HasColumnType("text");

                                    b2.Property<string>("Line2")
                                        .HasColumnType("text");

                                    b2.Property<string>("Line3")
                                        .HasColumnType("text");

                                    b2.Property<string>("Line4")
                                        .HasColumnType("text");

                                    b2.Property<string>("Postcode")
                                        .HasColumnType("text");

                                    b2.Property<string>("Town")
                                        .HasColumnType("text");

                                    b2.HasKey("CanonicalCustomerCanonicalOrderChannelKey", "CanonicalCustomerCanonicalOrderOrderNumber");

                                    b2.ToTable("Orders");

                                    b2.WithOwner()
                                        .HasForeignKey("CanonicalCustomerCanonicalOrderChannelKey", "CanonicalCustomerCanonicalOrderOrderNumber");
                                });

                            b1.Navigation("DeliveryAddress")
                                .IsRequired();
                        });

                    b.OwnsMany("Central.Core.Models.CanonicalOrderLine", "Lines", b1 =>
                        {
                            b1.Property<string>("CanonicalOrderChannelKey")
                                .HasColumnType("text");

                            b1.Property<string>("CanonicalOrderOrderNumber")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("LineRef")
                                .HasColumnType("text");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TaxCode")
                                .HasColumnType("text");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric");

                            b1.HasKey("CanonicalOrderChannelKey", "CanonicalOrderOrderNumber", "Id");

                            b1.ToTable("CanonicalOrderLine");

                            b1.WithOwner()
                                .HasForeignKey("CanonicalOrderChannelKey", "CanonicalOrderOrderNumber");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
